services:
  meet-us-there-db:
    image: postgres:18.1
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meet-us-there
    volumes:
      - pg-mut:/var/lib/postgresql

volumes:
  pg-mut:
